<style>
.project_details {
    float: left;
    list-style: none outside none;
    margin-left: -5px;
    xwidth: 277px;
}
</style>

<ul class="project_details">
	<li><strong><?= $this->t->_('Company Name'); ?>:</strong> <?= $this->content['portfolioName']; ?></li>
	<li><strong><?= $this->t->_('WWW'); ?>:</strong> <?= ($this->content['portfolioWWW'] == '') ? 'No web site, proprietary software' : 'http://' . $this->content['portfolioWWW'] ?> </li>
	<li><strong><?= $this->t->_('Description'); ?>:</strong> <?= $this->content['portfolioDescription']; ?></li>
</ul>
