 <div class="wrap">   
   <!--Main page posts -->
   <div class="main_page_posts">
      
    <div class="element1">
    <!--Begin contleft -->
    <div class="contleft"> 
     	<div class="left">
      <h2 style="text-align:right;"><?= $this->t->_('Profile'); ?><br/><span class="orange"><?= $this->t->_('EDUCATION'); ?></span></h2>		</div>
     </div>
     <!--End contleft -->     
   
        <!--  Begin post -->
        <div class="post">
        	<div class="post_content">
            	<div class="partcontent">
            	
            	<?php
            		$profile = str_replace('Spring 2006 &ndash; Spring 2011', $this->t->_('Spring 2006 &ndash; Spring 2011'), $this->content['profile']);
            		$profile = str_replace('Bachelors of Science in Computer Science, Minor in Mathematics', $this->t->_('Bachelors of Science in Computer Science, Minor in Mathematics'), $profile);
            		$profile = str_replace('Fall 2003 &ndash; Fall 2005', $this->t->_('Fall 2003 &ndash; Fall 2005'), $profile);
            		$profile = str_replace('Associates of Science in Computer Science, Minor in Mathematics', $this->t->_('Associates of Science in Computer Science, Minor in Mathematics'), $profile);
            		$profile = str_replace('Fall 2002 &ndash; Fall 2003', $this->t->_('Fall 2002 &ndash; Fall 2003'), $profile);
            		$profile = str_replace('Associates of Science in Engineering Science, Minor in Mathematics', $this->t->_('Associates of Science in Engineering Science, Minor in Mathematics'), $profile);
            		echo $profile; 
            	?>
				
				</div>
                  <!--  End content1 -->
            </div>
             <!--  End post_content -->    
        </div>
        <!--  End post -->
       
         </div>
          <!-- End contright -->
          <div style="clear:both">
       </div>
              
         <div class="element2">
   <div class="contleft"> 
     	<div class="left">
      <h2 style="text-align:right;"><?= $this->t->_('Work'); ?><br/><span class="orange"><?= $this->t->_('EXPERIENCE'); ?></span></h2>		</div>
     </div>
        
        <!--  Begin post -->
        <div class="post">
        	<div class="post_content">
            	<div class="partcontent">
            	
	              	<?= $this->content['work']; ?>			
				
            	</div>
                  <!--  End content1 -->
            </div>
        </div>
        <!--  End post -->
         </div>
                 
          <!-- End contright -->
          <div style="clear:both">
       </div>
       
             <div class="element4">
  
    <div class="contleft"> 
     	<div class="left">
      <h2 style="text-align:right;"><?= $this->t->_('Skill'); ?><br/><span class="orange"><?= $this->t->_('TECHNICAL'); ?></span></h2>		</div>
     </div>
        
        <!--  Begin post -->
        <div class="post">
        	<div class="post_content">
            	<div class="partcontent">            		
					<?= $this->content['skill']; ?>
            	</div>
                  <!--  End content1 -->                                    
            </div>
                                
        </div>
        <!--  End post -->  
       
         </div>
          <!-- End contright -->

          <div style="clear:both">
       </div>       
       
         <div class="element5">
   <div class="contleft"> 
     	<div class="left">
      <h2 style="text-align:right;"><?= $this->t->_('Contact'); ?><br/><span class="orange"><?= $this->t->_('ME'); ?></span></h2></div>
     </div>
        
        <!--  Begin post -->
        <div class="post">
        	<div class="post_content">
            	<div class="partcontent">
            	            	
            	<h3><?= $this->t->_('Please fill out the form'); ?></h3>
            		
            		<div class="result"></div>
            		
            		<?= $this->form; ?>
            		
                </div>
                  <!--  End content1 -->
            </div>
        </div>
        <!--  End post -->
         </div>
          <!-- End contright -->

          <div style="clear:both">
       </div>
        
   </div>
   <!-- End Main page posts -->
</div>

<script>
	$('#name').bind('blur', function() {
		if(this.value=='')this.value='<?= $this->t->_('Name'); ?>';
	});
	$('#name').bind('focus', function() {
		if(this.value=='<?= $this->t->_('Name'); ?>')this.value='';
	});	
	$('#email').bind('blur', function() {
		if(this.value=='')this.value='<?= $this->t->_('Email'); ?>';
	});
	$('#email').bind('focus', function() {
		if(this.value=='<?= $this->t->_('Email'); ?>')this.value='';
	});
	$('#message').bind('blur', function() {
		if(this.value=='')this.value='<?= $this->t->_('Message'); ?>';
	});
	$('#message').bind('focus', function() {
		if(this.value=='<?= $this->t->_('Message'); ?>')this.value='';
	});	

	$('.sponsor').bind('click', function() {
		portfolioItem($(this).attr('id'), $(this).attr('title'));	
	});	

	function contactFormSuccess(data)
	{
		if (!data.success)  {
			
			$('.result').html('<div class="error">' + data.fail + '</div>');		
		} else {
			
			$('.result').html("<div class=\"success\"><?= $this->t->_('Thank you for your email'); ?></div>");
		}		
	}

	function portfolioItem(id, title)
	{
		portfolioId = id;
		$("#portfolioItem").dialog('open');
		$("#portfolioItem").dialog({title: title});
				
		$.ajax( {
		        url: "/index/portfolio/id/" + portfolioId, 
		        success: function(returnData) { 
			        $('#portfolioItem').html(returnData);		           
		    	}
		       }
		    )   	
	}

	$(document).ready(function() {
		var options = {  
			url: '',
			success: contactFormSuccess,
			dataType : 'json'		
		};

		$('#<?= $this->form->getId() ?>').ajaxForm(options);

		
		$("#portfolioItem").dialog({
				resizable: false,
				autoOpen: false,
				modal: true,
				width: 450,
				height: 260,
				overlay: {
					backgroundColor: '#000',
					opacity: -25
				}		
			});		
		
		
	});
</script>