<div id="btn-logout-dialog" title="<?= $this->t->_('Exiting from Admin Panel'); ?>" style="display:none">
	<p><span class="ui-icon ui-icon-alert" style="float:left; margin:0 7px 20px 0;"></span>
	<?= $this->t->_('Are you sure you want to logout from the Administrator Panel?'); ?></p>
</div>

<div id="btn-myaccount-dialog" title="<?= $this->t->_('Account Settings are being changed'); ?>" style="display:none"></div>
<div id="btn-edituser-dialog" style="display:none"></div>

<div id="btn-deleteuser-dialog" title="<?= $this->t->_('User is being deleted'); ?>" style="display:none">
	<p><span class="ui-icon ui-icon-alert" style="float:left; margin:0 7px 20px 0;"></span>
	<?= $this->t->_('Are you sure you want to delete this user?'); ?></p>
</div>

<div id="btn-deletelist-dialog" title="<?= $this->t->_('Selected items are being deleted'); ?>" style="display:none">
	<p><span class="ui-icon ui-icon-alert" style="float:left; margin:0 7px 20px 0;"></span>
	<?= $this->t->_('Are you sure you want to delete these items?'); ?></p>
</div>

<div id="btn-cacheclear-dialog" title="<?= $this->t->_('Cache database will be truncated'); ?>" style="display:none">
	<p><span class="ui-icon ui-icon-alert" style="float:left; margin:0 7px 20px 0;"></span>
	<?= $this->t->_('Are you sure you want to clear the cache?'); ?></p>
</div>

<div id="lnk-showdetails-dialog" style="display:none"></div>