<script type="text/javascript">
$(document).ready(function() {

	$("#value").focus();

	var options = {  
		url: '<?= $this->form->getAction(); ?>',
        success: vkNgineAjaxFormSubmit,
		dataType : 'json'
    };
    
	$('#<?= $this->form->getId(); ?>').ajaxForm(options);
	
	$('body').removeClass('layout1280');
	$('body').addClass('layout1280');

	$('.vkNgineLabel').css('width', '120px');
	$('ul.vkNgineForm').css('width', '850px');
});
</script>
<script type="text/javascript" src="/js/tinymce/jquery.tinymce.js"></script>
<script type="text/javascript">
	$().ready(function() {
		$('textarea').tinymce({
			script_url : '/js/tinymce/tiny_mce_gzip.php',

			mode : "textareas",
			theme : "advanced",
			plugins : "autolink,lists,pagebreak,style,layer,table,save,advhr,advimage,advlink,emotions,iespell,inlinepopups,insertdatetime,preview,media,searchreplace,print,contextmenu,paste,directionality,fullscreen,noneditable,visualchars,nonbreaking,xhtmlxtras,template,advlist",
			
			theme_advanced_buttons1 : "newdocument,|,bold,italic,underline,strikethrough,|,justifyleft,justifycenter,justifyright,justifyfull,styleselect,formatselect,fontselect,fontsizeselect",
			theme_advanced_buttons2 : "cut,copy,paste,pastetext,pasteword,|,search,replace,|,bullist,numlist,|,outdent,indent,blockquote,|,undo,redo,|,insertdate,inserttime,|,forecolor,backcolor",
			theme_advanced_buttons3 : "insertlayer,absolute,|,styleprops,|,cite,abbr,acronym,del,ins,attribs,|,preview,code",
			theme_advanced_toolbar_location : "top",
			theme_advanced_toolbar_align : "left",
			theme_advanced_statusbar_location : "bottom",
			theme_advanced_resizing : true,

			width : "700",
				
			// Skin options
	        skin : "o2k7",
	        skin_variant : "silver",
			
			// Drop lists for link/image/media/template dialogs
			template_external_list_url : "lists/template_list.js",
			external_link_list_url : "lists/link_list.js",
			external_image_list_url : "lists/image_list.js",
			media_external_list_url : "lists/media_list.js",
		});
	});
</script>

<?= $this->partial('_breadcrumbs.phtml', array('breadcrumb' => $this->breadcrumb())); ?>

<div id="page-layout" class="fixed">
	<div id="page-content">
		<div id="page-content-wrapper">
			<div class="inner-page-title">
				<h2><?= $this->t->_('Content Management'); ?></h2>
				<span><?= $this->t->_('Here you can edit content pages'); ?></span>
			</div>
			<div class="hastable">
					<?= $this->form; ?>
				<div class="clear"></div>
			</div>
			
			<?= $this->partial('layout-sidebar.phtml', array('section' => 'content', 't' => $this->t, 'refreshLink' => $this->adminUrl(null, 'content') . '/index/contentId/' . $this->contentId))  ?> 	
					
	<div class="clear"></div>			
			</div>
		<div class="clear"></div>
	</div>
	</div>
	<div class="clear"></div>